apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zta
resources:
  - ../../base
  - ../../istio/peer-authentication.yaml
  - ../../istio/request-authentication.rendered.yaml   # generated: scripts/render-k8s-jwks.sh
  - ../../istio/authz-require-jwt.yaml
  - ../../istio/opa-extauthz.yaml
configMapGenerator:
  - name: app-config
    behavior: merge
    literals: [JWT_MODE=delegated, AUTH_MODE=delegated, SCENARIO=S5]
  - name: opa-policy
    files: [authz.rego=../../../policy/authz.rego]
  - name: opa-config
    files: [opa-envoy-config.yaml=../../../policy/opa-envoy-config.yaml]
generatorOptions: { disableNameSuffixHash: true }
