apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zta
resources:
  - ../../base
  - ../../istio/peer-authentication.yaml
  - ../../istio/request-authentication.rendered.yaml   # generated: scripts/render-k8s-jwks.sh
  - ../../istio/authz-require-jwt.yaml
configMapGenerator:
  - name: app-config
    behavior: merge
    literals: [JWT_MODE=delegated, AUTH_MODE=none, SCENARIO=S4]
generatorOptions: { disableNameSuffixHash: true }
