#!/usr/bin/env bash
# Render RequestAuthentication with the JWKS inlined from envoy/jwks.json.
#
# The committed manifest carries a jwksUri placeholder. Istio cannot fetch it,
# and rather than failing it falls back to a FAKE JWKS -- so every real token is
# rejected and the run silently produces 100% false positives. Inlining the keys
# (what scripts/k8s-setup.sh's own note recommends) removes the fetch entirely.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="k8s/istio/request-authentication.yaml"
OUT="k8s/istio/request-authentication.rendered.yaml"
[ -f envoy/jwks.json ] || { echo "envoy/jwks.json missing - run: make keys" >&2; exit 1; }

python3 - "$SRC" "$OUT" <<'PY'
import json, sys
src, out = sys.argv[1], sys.argv[2]
jwks = json.dumps(json.load(open('envoy/jwks.json')), separators=(',', ':'))
lines = []
for line in open(src):
    if 'jwksUri:' in line:
        indent = line[:len(line) - len(line.lstrip())]
        lines.append(f"{indent}jwks: {json.dumps(jwks)}\n")   # inline, generated
    else:
        lines.append(line)
open(out, 'w').write(
    "# GENERATED by scripts/render-k8s-jwks.sh - do not edit, do not commit.\n"
    + "".join(lines))
print(f"wrote {out} with {len(json.loads(jwks)['keys'])} inline keys")
PY
