apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zta
resources:
  - ../../base
  - ../../istio/peer-authentication.yaml
configMapGenerator:
  - name: app-config
    behavior: merge
    literals: [JWT_MODE=app, AUTH_MODE=app, JWT_ALG=RS256, SCENARIO=S3]
generatorOptions: { disableNameSuffixHash: true }
