"""
Emit the paper's LaTeX tables and a macro file straight from the result CSVs.

Nothing in the paper should be transcribed by hand: every number a reviewer can
check is generated here from results/*.csv, so a re-run updates the manuscript
rather than silently disagreeing with it. Writes into paper/generated/.

  tab_scenarios.tex   scenario matrix (static definition, from compose/scenarios)
  tab_elbow.tex       per-scenario elbow + provenance
  tab_cost.tex        coverage vs cost at the elbow
  tab_blockrates.tex  per-risk block rate with 95% CI over trials
  macros.tex          \newcommand for every number cited in prose
"""
import os, re, sys
import numpy as np, pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import RISKS, SCENARIO_LABELS

OUT = "paper/generated"
CORE = ["S0", "S1", "S2", "S3", "S4", "S5", "S6"]
ARMS = ["S0rl", "S3off", "S4es", "S6fo", "S6oc", "S6fooc"]


def esc(s):
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def fmt(x, nd=2, dash="--"):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return dash
    return f"{x:.{nd}f}"


def macro_name(s):
    """A LaTeX macro name may only contain letters."""
    words = re.sub(r"[^A-Za-z0-9]+", " ", str(s)).split()
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    out = ""
    for w in words:
        w = w[0].upper() + w[1:]
        out += "".join(digits.get(c, c) for c in w)
    return out


class Macros:
    def __init__(self):
        self.items = {}

    def add(self, name, value):
        self.items[macro_name(name)] = value

    def write(self, path):
        lines = ["% Auto-generated by analysis/make_latex.py -- do not edit.",
                 "% Every number cited in the manuscript resolves through here.", ""]
        for k, v in sorted(self.items.items()):
            lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
        open(path, "w").write("\n".join(lines) + "\n")
        return len(self.items)


def table(caption, label, header, rows, colspec, note=None):
    out = ["\\begin{table}[t]", "\\centering",
           f"\\caption{{{caption}}}", f"\\label{{{label}}}",
           "\\small",
           f"\\begin{{tabular}}{{{colspec}}}", "\\toprule",
           " & ".join(header) + " \\\\", "\\midrule"]
    out += [" & ".join(r) + " \\\\" for r in rows]
    out += ["\\bottomrule", "\\end{tabular}"]
    if note:
        out += [f"\\\\[2pt]\\footnotesize {note}"]
    out += ["\\end{table}", ""]
    return "\n".join(out)


def scenario_table():
    """Read the compose scenario definitions so the table cannot drift from
    what was actually executed."""
    rows = []
    for scn in CORE + ARMS:
        p = f"compose/scenarios/{scn}.env"
        if not os.path.exists(p):
            continue
        env = dict(l.strip().split("=", 1) for l in open(p)
                   if "=" in l and not l.strip().startswith("#"))
        jwt = {"none": "--", "app": "app", "delegated": "sidecar"}.get(env.get("APP_JWT_MODE"), "?")
        authz = {"none": "--", "app": "app", "delegated": "OPA"}.get(env.get("APP_AUTH_MODE"), "?")
        rate = env.get("NGINX_RATE", "--")
        rate = "--" if rate == "100000" else rate
        extra = []
        if env.get("APP_OFFLOAD") == "true":
            extra.append("worker offload")
        if "failopen" in env.get("ENVOY_CONFIG", ""):
            extra.append("fail-open")
        if env.get("APP_JWT_ALG") != "RS256":
            extra.append(env.get("APP_JWT_ALG", ""))
        rows.append([esc(scn), esc(SCENARIO_LABELS.get(scn, scn)), jwt, authz,
                     esc(rate), esc(", ".join(extra) or "--")])
    return table("Scenario matrix. JWT and authorization columns give the "
                 "enforcement point; the independent variable of the study.",
                 "tab:scenarios",
                 ["ID", "Description", "JWT at", "Authz at", "Rate limit (rps)", "Notes"],
                 rows, "llllll")


def elbow_table(macros):
    p = "results/elbow_table.csv"
    if not os.path.exists(p):
        return ""
    df = pd.read_csv(p)
    rows = []
    for _, r in df.sort_values("scenario").iterrows():
        est = np.isfinite(r.op_elbow_rps) if pd.notna(r.op_elbow_rps) else False
        rows.append([esc(r.scenario), fmt(r.baseline_p99),
                     fmt(r.op_elbow_rps, 0) if est else "not reached",
                     fmt(r.mu_hat_rps, 0), fmt(r.max_p99, 1),
                     esc(r.get("provenance", "?"))])
        macros.add(f"{r.scenario} baseline p", fmt(r.baseline_p99))
        macros.add(f"{r.scenario} elbow", fmt(r.op_elbow_rps, 0) if est else "not reached")
        macros.add(f"{r.scenario} max p", fmt(r.max_p99, 1))
    return table("Per-scenario saturation elbow. The operational elbow is the "
                 "lowest offered load at which median $p_{99}$ exceeds twice the "
                 "low-load baseline; ``not reached'' means the sweep grid never "
                 "crossed that threshold, and the elbow is therefore unestimable "
                 "from this data rather than located at the grid edge.",
                 "tab:elbow",
                 ["Scenario", "Baseline $p_{99}$ (ms)", "Elbow (rps)",
                  "$\\hat{\\mu}$ (rps)", "Max $p_{99}$ (ms)", "Data"],
                 rows, "lrrrrl")


def cost_table(macros):
    p = "results/table_coverage_cost.csv"
    if not os.path.exists(p):
        return ""
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        rows.append([esc(r.scenario), esc(SCENARIO_LABELS.get(r.scenario, r.scenario)),
                     fmt(r.p50_ms), fmt(r.p99_ms), fmt(r.added_p99_ms),
                     fmt(r.coverage_pct, 1), fmt(r.fpr_pct, 2)])
        macros.add(f"{r.scenario} p fifty", fmt(r.p50_ms))
        macros.add(f"{r.scenario} p ninetynine", fmt(r.p99_ms))
        macros.add(f"{r.scenario} added p", fmt(r.added_p99_ms))
        macros.add(f"{r.scenario} coverage", fmt(r.coverage_pct, 1))
        macros.add(f"{r.scenario} fpr", fmt(r.fpr_pct, 2))
    return table("Security coverage versus latency cost at the elbow. Coverage "
                 "and FPR are pooled over risks and trials (descriptive point "
                 "estimates); interval estimates are in Table~\\ref{tab:blockrates}.",
                 "tab:cost",
                 ["ID", "Description", "$p_{50}$", "$p_{99}$", "$\\Delta p_{99}$",
                  "Coverage (\\%)", "FPR (\\%)"],
                 rows, "llrrrrr")


def blockrate_table(macros):
    p = "results/block_rates.csv"
    if not os.path.exists(p):
        return ""
    df = pd.read_csv(p)
    scns = [s for s in CORE + ARMS if s in set(df.scenario)]
    rows = []
    for risk in RISKS:
        sub = df[df.risk == risk]
        if sub.empty:
            continue
        cells = []
        for s in scns:
            r = sub[sub.scenario == s]
            if r.empty:
                cells.append("--"); continue
            r = r.iloc[0]
            cells.append(fmt(r.block_rate, 3))
            macros.add(f"{s} {risk} block", fmt(r.block_rate, 3))
            if pd.notna(r.ci_lo):
                macros.add(f"{s} {risk} ci", f"[{fmt(r.ci_lo,3)}, {fmt(r.ci_hi,3)}]")
        rows.append([esc(risk)] + cells)
    note = ("Block rate = TP/(TP+FN), the share of attacks correctly denied. "
            "The independent unit is the trial; 95\\% intervals over trials are "
            "in \\texttt{results/block\\_rates.csv}.")
    return table("Attack block rate per risk and scenario at the elbow.",
                 "tab:blockrates", ["Risk"] + [esc(s) for s in scns],
                 rows, "l" + "r" * len(scns), note)


def stats_macros(macros):
    """Pull the headline inferential numbers out of the generated report so the
    prose cites exactly what the pipeline computed."""
    p = "results/stats_report.md"
    if not os.path.exists(p):
        return
    txt = open(p).read()
    m = re.search(r"F = ([\d.]+), p = ([\d.e+-]+) \(Holm-adjusted p = ([\d.e+-]+)\), eta\^2 = ([\d.]+)", txt)
    if m:
        macros.add("anova F", m.group(1)); macros.add("anova P", m.group(2))
        macros.add("anova Padj", m.group(3)); macros.add("anova Etasq", m.group(4))
    for a, b, tag in [("S3", "S4", "RQone"), ("S4", "S4es", "RQtwo")]:
        m = re.search(rf"{a} vs {b} \(p99\)\)?, Cohen", txt)
        m = re.search(r"Welch t = ([-\d.]+), p = ([\d.e+-]+) \(Holm-adjusted p = "
                      r"([\d.e+-]+)\), Cohen's d = ([-\d.]+)", txt[txt.find(f"- {a}: mean p99"):]
                      if f"- {a}: mean p99" in txt else "")
        if m:
            macros.add(f"{tag} t", m.group(1)); macros.add(f"{tag} P", m.group(2))
            macros.add(f"{tag} Padj", m.group(3)); macros.add(f"{tag} D", m.group(4))
    m = re.search(r"Mann-Whitney U = ([\d.]+), p = ([\d.e+-]+) \(Holm-adjusted p = "
                  r"([\d.e+-]+)\), rank-biserial r = ([-\d.]+)", txt)
    if m:
        macros.add("bola U", m.group(1)); macros.add("bola P", m.group(2))
        macros.add("bola Padj", m.group(3)); macros.add("bola R", m.group(4))


def main():
    os.makedirs(OUT, exist_ok=True)
    macros = Macros()

    runs_p = "results/tidy_runs.csv"
    if os.path.exists(runs_p):
        runs = pd.read_csv(runs_p)
        macros.add("n runs", len(runs))
        macros.add("n trials", int(runs.groupby(["scenario", "load_rps"]).size().max()))
        macros.add("n scenarios", runs.scenario.nunique())
        macros.add("n requests", f"{int(runs.http_reqs.sum()):,}".replace(",", "{,}"))
        prov = runs.get("synthetic", pd.Series([False]))
        macros.add("data provenance", "synthetic" if prov.all()
                   else "mixed" if prov.any() else "measured")
        loads = sorted(runs.load_rps.unique())
        macros.add("load grid", ", ".join(str(int(x)) for x in loads))
    if os.path.exists("results/lambda_star.txt"):
        macros.add("lambda star", open("results/lambda_star.txt").read().strip())

    files = {
        "tab_scenarios.tex": scenario_table(),
        "tab_elbow.tex": elbow_table(macros),
        "tab_cost.tex": cost_table(macros),
        "tab_blockrates.tex": blockrate_table(macros),
    }
    stats_macros(macros)

    written = []
    for name, body in files.items():
        if body:
            open(os.path.join(OUT, name), "w").write(body)
            written.append(name)
    n = macros.write(os.path.join(OUT, "macros.tex"))
    written.append("macros.tex")
    print(f"wrote {len(written)} files to {OUT}/ ({n} macros): {', '.join(written)}")


if __name__ == "__main__":
    main()
